import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <nav style={{ padding: "1rem 2rem", borderBottom: "1px solid #333" }}>
          <Link href="/" style={{ marginRight: "1rem" }}>
            thoughts
          </Link>
          <Link href="/admin">admin</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
